// Generated questionnaire choices transcribed from docs/survey-questionnaire.md.
// Observed workbook values and proposed additions remain separate in that document.
export const PASIG_BARANGAYS = [
  "Bagong Ilog",
  "Bagong Katipunan",
  "Bambang",
  "Buting",
  "Caniogan",
  "Dela Paz",
  "Kalawaan",
  "Kapasigan",
  "Kapitolyo",
  "Malinao",
  "Manggahan",
  "Maybunga",
  "Oranbo",
  "Palatiw",
  "Pinagbuhatan",
  "Pineda",
  "Rosario",
  "Sagad",
  "San Antonio",
  "San Joaquin",
  "San Jose",
  "San Miguel",
  "San Nicolas",
  "Santa Cruz",
  "Santa Lucia",
  "Santa Rosa",
  "Santolan",
  "Santo Tomas",
  "Sumilang",
  "Ugong",
] as const

export const JOB_INDUSTRY_CATEGORIES: Record<string, string[]> = {
  "Accounting": [
    "Accounts Receivable/Credit Control",
    "Audit – External",
    "Financial Accounting & Reporting",
    "Forensic Accounting & Investigation",
    "Accounts Payable",
    "Bookkeeping",
    "Internal Audit",
    "Payroll",
    "Taxation",
    "Other (specify)",
  ],
  "Administration & Office Support": [
    "Administrative Assistants",
    "Records Management & Document Control",
    "Reception/front desk",
    "Executive/secretarial support",
    "Data entry",
    "Client/sales administration",
    "Contracts administration",
    "Other (specify)",
  ],
  "Advertising, Arts, & Media": [
    "Editing & Publishing",
    "Creative direction/design",
    "Journalism/writing",
    "Media planning/buying",
    "Photography/video production",
    "Events/promotions",
    "Performing arts",
    "Other (specify)",
  ],
  "Banking & Financial Services": [
    "Analysis & Reporting",
    "Banking – Retail/Branch",
    "Management",
    "Business banking",
    "Credit/lending",
    "Financial planning",
    "Compliance/risk",
    "Client account management",
    "Other (specify)",
  ],
  "Call Centre & Customer Service": [
    "Customer Service – Call Centre",
    "Customer Service – Customer Facing",
    "Sales – Outbound",
    "Supervisors/Team Leaders",
    "Inbound sales",
    "Collections",
    "Quality assurance/training",
    "Customer-service management/support",
    "Other (specify)",
  ],
  "CEO & General Management": [
    "Board/governance appointments",
    "Chief executive leadership",
    "Chief operating/managing director roles",
    "General/business unit management",
    "Other executive management (specify)",
    "Other (specify)",
  ],
  "Community Services & Development": [
    "Management",
    "Social work/case management",
    "Youth/family services",
    "Community development",
    "Disability/aged-care support",
    "Fundraising/nonprofit programs",
    "Other (specify)",
  ],
  "Construction": [
    "Management",
    "Site supervision",
    "Project management",
    "Estimating/costing",
    "Contracts administration",
    "Surveying",
    "Safety/compliance",
    "Other (specify)",
  ],
  "Consulting & Strategy": [
    "Business analysis",
    "Corporate development",
    "Environment/sustainability advisory",
    "Management/change consulting",
    "Policy advisory",
    "Strategy/planning",
    "Other consulting (specify)",
    "Other (specify)",
  ],
  "Design & Architecture": [
    "Architecture",
    "Architectural drafting",
    "Graphic/visual design",
    "Industrial/product design",
    "Interior design",
    "Landscape/urban design",
    "Web/interaction design",
    "Other design (specify)",
    "Other (specify)",
  ],
  "Education & Training": [
    "Management – Schools",
    "Management – Universities",
    "Teaching – Early Childhood",
    "Teaching – Primary",
    "Teaching – Secondary",
    "Tutoring",
    "Workplace Training & Assessment",
    "Other (specify)",
  ],
  "Engineering": [
    "Civil/structural engineering",
    "Electrical/electronics engineering",
    "Mechanical engineering",
    "Chemical/process engineering",
    "Environmental engineering",
    "Industrial engineering",
    "Engineering drafting/design",
    "Project/field engineering",
    "Engineering maintenance",
    "Other engineering (specify)",
    "Other (specify)",
  ],
  "Farming, Animals & Conservation": [
    "Agronomy/farm services",
    "Farm operations",
    "Horticulture",
    "Fisheries/aquaculture",
    "Animal care/veterinary services",
    "Conservation/parks/wildlife",
    "Other agriculture/conservation (specify)",
    "Other (specify)",
  ],
  "Government & Defense": [
    "Emergency Services",
    "Government – Local",
    "Government – National",
    "Government – Regional/Provincial",
    "Armed Forces",
    "Police/corrections",
    "Policy/planning/regulation",
    "Public administration",
    "Other (specify)",
  ],
  "Healthcare & Medical": [
    "Medical Administration",
    "Nursing - A&E, Critical Care & ICU",
    "Nursing - General Medical & Surgical",
    "Pharmaceuticals & Medical Devices",
    "Allied health/rehabilitation",
    "Dental care",
    "Laboratory/pathology",
    "Medical imaging",
    "Pharmacy",
    "Public/community health",
    "Other (specify)",
  ],
  "Hospitality & Tourism": [
    "Bar & Beverages Staff",
    "Chefs/Cooks",
    "Front Office & Guest Services",
    "Management",
    "Travel Agents/Consultants",
    "Other (specify)",
  ],
  "Human Resources & Recruitment": [
    "Management - Agency",
    "Agency recruitment",
    "In-house recruitment",
    "Employee relations",
    "Training/development",
    "HR generalist services",
    "Organizational development",
    "Other (specify)",
  ],
  "Information & Communication Technology": [
    "Developers/Programmers",
    "Engineering - Network",
    "Help Desk & IT Support",
    "Management",
    "Networks & Systems Administration",
    "Programme & Project Management",
    "Sales - Pre & Post",
    "Telecommunications",
    "Testing & Quality Assurance",
    "Other (specify)",
  ],
  "Insurance & Superannuation": [
    "Management",
    "Underwriting",
    "Claims processing",
    "Brokerage",
    "Risk/actuarial analysis",
    "Policy administration",
    "Retirement benefits/fund administration",
    "Other (specify)",
  ],
  "Legal": [
    "Corporate/commercial law",
    "Civil/criminal litigation",
    "Family law",
    "Labor/employment law",
    "Property/construction law",
    "In-house legal/compliance",
    "Paralegal/legal assistance",
    "Legal administration",
    "Other legal services (specify)",
    "Other (specify)",
  ],
  "Manufacturing, Transport & Logistics": [
    "Purchasing, Procurement & Inventory",
    "Production/assembly",
    "Quality assurance/control",
    "Warehousing/distribution",
    "Freight/transport",
    "Machine operations",
    "Supply-chain planning",
    "Other (specify)",
  ],
  "Marketing & Communications": [
    "Digital & Search Marketing",
    "Marketing Assitants/Coordinators",
    "Brand management",
    "Public relations",
    "Market research/analysis",
    "Events marketing",
    "Content/communications",
    "Product marketing",
    "Other (specify)",
  ],
  "Mining, Resources & Energy": [
    "Mining operations",
    "Mineral exploration/geoscience",
    "Mine engineering/maintenance",
    "Oil/gas operations",
    "Power/energy generation",
    "Health/safety/environment",
    "Natural resources/water",
    "Other resources/energy (specify)",
    "Other (specify)",
  ],
  "Real Estate & Property": [
    "Administration",
    "Residential Sales",
    "Property management/leasing",
    "Commercial sales/leasing",
    "Facilities management",
    "Property valuation",
    "Property development",
    "Other (specify)",
  ],
  "Retail & Consumer Products": [
    "Buying",
    "Management - Area/Multi-site",
    "Merchandisers",
    "Retail Assistants",
    "Store management",
    "Customer service/cashiering",
    "Inventory/stock control",
    "E-commerce/online retail",
    "Other (specify)",
  ],
  "Sales": [
    "Management",
    "Sales Coordinators",
    "Sales Representatives/Consultants",
    "Account/relationship management",
    "Business development",
    "Retail/in-store sales",
    "Technical sales",
    "Sales analysis/operations",
    "Other (specify)",
  ],
  "Science & Technology": [
    "Quality Assurance & Control",
    "Laboratory/technical services",
    "Biological/biomedical sciences",
    "Food technology/safety",
    "Chemistry/physics",
    "Environmental/earth sciences",
    "Research/data analysis",
    "Other (specify)",
  ],
  "Self-Employment": [
    "Self Employment",
    "Retail/trading business",
    "Food-service business",
    "Freelance professional services",
    "Digital/online business",
    "Skilled-trade services",
    "Other (specify)",
  ],
  "Sport & Recreation": [
    "Sports coaching/instruction",
    "Fitness/personal training",
    "Sports/recreation management",
    "Recreation program delivery",
    "Other sport/recreation (specify)",
    "Other (specify)",
  ],
  "Trades & Services": [
    "Electrical trades",
    "Automotive trades",
    "Carpentry/building trades",
    "Plumbing",
    "Welding/fabrication",
    "Air conditioning/refrigeration",
    "Maintenance/repair technicians",
    "Cleaning/facilities services",
    "Gardening/landscaping",
    "Hair/beauty services",
    "Security services",
    "Other trades/services (specify)",
    "Other (specify)",
  ],
}

export const JOB_INDUSTRIES = Object.keys(JOB_INDUSTRY_CATEGORIES)
export const JOB_CATEGORY_OPTIONS = [...new Set(Object.values(JOB_INDUSTRY_CATEGORIES).flat())]
export const JOB_CATEGORY_OTHER_OPTIONS = JOB_CATEGORY_OPTIONS.filter((option) =>
  option.startsWith("Other") && option.endsWith("(specify)"),
)

export const JOB_TITLES = [
  "Account Executive",
  "Accounting Role",
  "Accounts Manager",
  "Administration Role",
  "Administrative Manager",
  "Administrative Officer",
  "Agent",
  "Analyst",
  "Architect",
  "Assistant",
  "Audit Associate",
  "Back Office Staff",
  "Bank Teller",
  "Barista",
  "Billing Specialist",
  "Bookkeeper",
  "Business Development Executive",
  "Cashier",
  "Chef/Cook",
  "Commis Chef",
  "Compliance Officer",
  "Consultant",
  "Coordinator",
  "Crew Member",
  "Customer Service Representative",
  "Data Encoder",
  "Data Entry Role",
  "Designer",
  "Early Childhood Teacher",
  "Educational Leader",
  "Educator",
  "Engineer",
  "Engineering Role",
  "English Teacher",
  "Executive",
  "Farmer",
  "Financial Advisor",
  "Fitness Instructor",
  "Freelancer/Independent Professional",
  "Frontliner",
  "Full Stack Developer",
  "Head Teacher",
  "Healthcare Professional",
  "High School Teacher",
  "Hospitality Worker",
  "Human Resources Assistant",
  "Human Resources Officer",
  "Identity and Access Management Officer",
  "Insurance Officer",
  "Internal Auditor",
  "Laboratory Technician",
  "Lawyer/Attorney",
  "Logistics Officer",
  "Machine Operator",
  "Management Trainee",
  "Manager",
  "Marketing Assistant",
  "Marketing Officer",
  "Medical Representative",
  "Merchandiser",
  "Mining Worker",
  "Multimedia Designer",
  "Network Engineer",
  "Nurse",
  "Online English Teacher",
  "Online Seller",
  "Owner",
  "Paralegal",
  "Police Officer",
  "Project Coordinator",
  "Property Manager",
  "Quality Analyst",
  "Quality Assurance Engineer",
  "Quality Assurance Role",
  "Real Estate Agent",
  "Researcher",
  "Sales Assistant",
  "Sales Associate",
  "Sales Engineer",
  "Sales Executive",
  "Sales Manager",
  "Sales Supervisor",
  "Scientist",
  "Security Guard",
  "Skilled Tradesperson",
  "Social Media Manager",
  "Social Worker",
  "Software Developer",
  "Specialist",
  "Sports Coach",
  "Staff Nurse",
  "Store Crew",
  "Store Manager",
  "Supply Chain Officer",
  "Support Engineer",
  "Systems Developer",
  "Teacher I-VII",
  "Technical Officer",
  "Technician",
  "Tour Consultant",
  "Trainer",
  "Veterinarian",
  "Worker",
  "Other job title (specify)",
] as const
