"""align survey field defaults

Revision ID: 253b93362366
Revises: ce4ef68a700d
Create Date: 2026-08-21 13:51:32.685078
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '253b93362366'
down_revision = 'ce4ef68a700d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_questions', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_questions', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
