"""Add ml_sentiments to survey_responses

Revision ID: 3aad20b0fc8a
Revises: f88b9c1d0000
Create Date: 2026-09-03 00:42:42.951834
"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3aad20b0fc8a'
down_revision = 'f88b9c1d0000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('ml_sentiments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('surveys', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('survey_responses', 'ml_sentiments')
    # ### end Alembic commands ###
