"""add survey sections table

Revision ID: 3f3ca600cf33
Revises: f95484540958
Create Date: 2026-07-11 15:11:03.015415
"""

import uuid

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3f3ca600cf33'
down_revision = 'f95484540958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_sections_id'), 'survey_sections', ['id'], unique=False)
    op.create_index(
        op.f('ix_survey_sections_is_deleted'), 'survey_sections', ['is_deleted'], unique=False
    )
    op.create_index(
        op.f('ix_survey_sections_order_index'), 'survey_sections', ['order_index'], unique=False
    )
    op.create_index(
        op.f('ix_survey_sections_performed_by'), 'survey_sections', ['performed_by'], unique=False
    )
    op.create_index(
        op.f('ix_survey_sections_survey_id'), 'survey_sections', ['survey_id'], unique=False
    )
    op.add_column('survey_questions', sa.Column('section_id', sa.Uuid(), nullable=True))
    op.alter_column('survey_questions', 'question_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(
        op.f('ix_survey_questions_section_id'), 'survey_questions', ['section_id'], unique=False
    )
    op.create_foreign_key(
        'fk_survey_questions_section_id',
        'survey_questions',
        'survey_sections',
        ['section_id'],
        ['id'],
    )
    # ### end Alembic commands ###

    # Backfill: create a default section for every survey that has questions
    conn = op.get_bind()
    now = sa.func.now()
    rows = conn.execute(
        sa.text(
            "SELECT DISTINCT sq.survey_id FROM survey_questions sq "
            "WHERE sq.is_deleted = false AND sq.section_id IS NULL"
        )
    ).fetchall()
    for (survey_id,) in rows:
        section_id = uuid.uuid4()
        conn.execute(
            sa.text(
                "INSERT INTO survey_sections "
                "(id, created_at, updated_at, is_deleted, survey_id, "
                "title, description, order_index) "
                "VALUES (:id, :now, :now, false, :survey_id, :title, NULL, 0)"
            ),
            {"id": section_id, "now": now, "survey_id": survey_id, "title": "Section 1"},
        )
        conn.execute(
            sa.text(
                "UPDATE survey_questions SET section_id = :section_id "
                "WHERE survey_id = :survey_id AND section_id IS NULL"
            ),
            {"section_id": section_id, "survey_id": survey_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_survey_questions_section_id', 'survey_questions', type_='foreignkey'
    )
    op.drop_index(op.f('ix_survey_questions_section_id'), table_name='survey_questions')
    op.alter_column('survey_questions', 'question_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('survey_questions', 'section_id')
    op.drop_index(op.f('ix_survey_sections_survey_id'), table_name='survey_sections')
    op.drop_index(op.f('ix_survey_sections_performed_by'), table_name='survey_sections')
    op.drop_index(op.f('ix_survey_sections_order_index'), table_name='survey_sections')
    op.drop_index(op.f('ix_survey_sections_is_deleted'), table_name='survey_sections')
    op.drop_index(op.f('ix_survey_sections_id'), table_name='survey_sections')
    op.drop_table('survey_sections')
    # ### end Alembic commands ###
