"""add response idempotency integrity

Revision ID: 6a181ceb76f6
Revises: 57bac44948be
Create Date: 2026-08-21 14:37:57.295170
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6a181ceb76f6'
down_revision = '57bac44948be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_survey_distributions_owner_reference",
        "survey_distributions",
        ["id", "survey_id", "version_id"],
    )
    op.add_column(
        "survey_responses", sa.Column("idempotency_key", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "survey_responses",
        sa.Column("idempotency_hash", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_survey_responses_distribution_id"),
        "survey_responses",
        ["distribution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_survey_responses_idempotency_key"),
        "survey_responses",
        ["idempotency_key"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_survey_responses_distribution_idempotency",
        "survey_responses",
        ["distribution_id", "idempotency_key"],
    )
    op.drop_constraint(
        op.f("survey_responses_distribution_id_fkey"),
        "survey_responses",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_survey_responses_distribution_owner",
        "survey_responses",
        "survey_distributions",
        ["distribution_id", "survey_id", "version_id"],
        ["id", "survey_id", "version_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_survey_responses_distribution_owner",
        "survey_responses",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("survey_responses_distribution_id_fkey"),
        "survey_responses",
        "survey_distributions",
        ["distribution_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_survey_responses_distribution_idempotency",
        "survey_responses",
        type_="unique",
    )
    op.drop_index(op.f('ix_survey_responses_idempotency_key'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_distribution_id'), table_name='survey_responses')
    op.drop_column('survey_responses', 'idempotency_hash')
    op.drop_column('survey_responses', 'idempotency_key')
    op.drop_constraint(
        "uq_survey_distributions_owner_reference",
        "survey_distributions",
        type_="unique",
    )
    # ### end Alembic commands ###
