"""require survey owner

Revision ID: 6f8d7931d7ad
Revises: de31b342df3f
Create Date: 2026-08-23 17:22:39.591265
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f8d7931d7ad"
down_revision = "de31b342df3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("surveys", "owner_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("surveys", "owner_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
