"""store response answers as json

Revision ID: 72bd1300e341
Revises: 8f0e30bf5973
Create Date: 2026-08-21 14:44:01.581334
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '72bd1300e341'
down_revision = '8f0e30bf5973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "survey_responses",
        "answers",
        existing_type=sa.VARCHAR(length=10000),
        type_=postgresql.JSONB(),
        existing_nullable=False,
        postgresql_using="answers::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "survey_responses",
        "answers",
        existing_type=postgresql.JSONB(),
        type_=sa.VARCHAR(length=10000),
        existing_nullable=False,
        postgresql_using="answers::text",
    )
    # ### end Alembic commands ###
