"""remove survey collaboration

Revision ID: 81568591615f
Revises: 505590bf8f96
Create Date: 2026-08-24 22:24:35.196535
"""

from typing import Any

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '81568591615f'
down_revision = '505590bf8f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_memberships_id'), table_name='survey_memberships')
    op.drop_index(op.f('ix_survey_memberships_is_deleted'), table_name='survey_memberships')
    op.drop_index(op.f('ix_survey_memberships_performed_by'), table_name='survey_memberships')
    op.drop_index(op.f('ix_survey_memberships_survey_id'), table_name='survey_memberships')
    op.drop_index(op.f('ix_survey_memberships_user_id'), table_name='survey_memberships')
    op.drop_table('survey_memberships')
    op.drop_index(op.f('ix_surveys_owner_id'), table_name='surveys')
    op.drop_constraint(op.f('fk_surveys_owner_id_users'), 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'owner_id')
    # ### end Alembic commands ###
    obsolete_codes = (
        "surveys.access_all",
        "surveys.read",
        "surveys.create",
        "surveys.update",
        "surveys.publish",
        "surveys.delete",
        "surveys.restore",
        "surveys.share",
        "surveys.transfer",
        "survey_structure.manage",
        "survey_distributions.read",
        "survey_distributions.manage",
        "survey_distributions.read_token",
        "survey_responses.read_raw",
    )
    bind = op.get_bind()
    permission_ids: Any = sa.select(sa.column("id")).select_from(
        sa.table("permissions", sa.column("id"), sa.column("code"))
    ).where(sa.column("code").in_(obsolete_codes))
    bind.execute(
        sa.delete(sa.table("role_permissions", sa.column("permission_id"))).where(
            sa.column("permission_id").in_(permission_ids)
        )
    )
    bind.execute(
        sa.delete(sa.table("permissions", sa.column("code"))).where(
            sa.column("code").in_(obsolete_codes)
        )
    )


def downgrade() -> None:
    # Reintroducing access controls after their data and APIs are deleted is unsupported.
    pass
