"""enforce one active survey version

Revision ID: 8f0e30bf5973
Revises: 6a181ceb76f6
Create Date: 2026-08-21 14:41:23.321563
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8f0e30bf5973'
down_revision = '6a181ceb76f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_survey_versions_active_draft",
        "survey_versions",
        ["survey_id"],
        unique=True,
        postgresql_where=sa.text("status = 'draft' AND is_deleted = false"),
        sqlite_where=sa.text("status = 'draft' AND is_deleted = 0"),
    )
    op.create_index(
        "uq_survey_versions_active_published",
        "survey_versions",
        ["survey_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published' AND is_deleted = false"),
        sqlite_where=sa.text("status = 'published' AND is_deleted = 0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_survey_versions_active_published",
        table_name="survey_versions",
        postgresql_where=sa.text("status = 'published' AND is_deleted = false"),
        sqlite_where=sa.text("status = 'published' AND is_deleted = 0"),
    )
    op.drop_index(
        "uq_survey_versions_active_draft",
        table_name="survey_versions",
        postgresql_where=sa.text("status = 'draft' AND is_deleted = false"),
        sqlite_where=sa.text("status = 'draft' AND is_deleted = 0"),
    )
    # ### end Alembic commands ###
