"""Add polarity_override to false_positive_feedbacks

Revision ID: a6c42481a0d9
Revises: b0d864b9935b
Create Date: 2026-09-03 04:31:43.567639
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a6c42481a0d9'
down_revision = 'b0d864b9935b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('false_positive_feedbacks', sa.Column('polarity_override', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('false_positive_feedbacks', 'polarity_override')
    # ### end Alembic commands ###
