"""Add false_positive_feedbacks

Revision ID: b0d864b9935b
Revises: 3aad20b0fc8a
Create Date: 2026-09-03 03:12:30.836854
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b0d864b9935b'
down_revision = '3aad20b0fc8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('false_positive_feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_false_positive_feedbacks_id'), 'false_positive_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_false_positive_feedbacks_is_deleted'), 'false_positive_feedbacks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_false_positive_feedbacks_performed_by'), 'false_positive_feedbacks', ['performed_by'], unique=False)
    op.create_index(op.f('ix_false_positive_feedbacks_question_id'), 'false_positive_feedbacks', ['question_id'], unique=False)
    op.create_index(op.f('ix_false_positive_feedbacks_response_id'), 'false_positive_feedbacks', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_false_positive_feedbacks_response_id'), table_name='false_positive_feedbacks')
    op.drop_index(op.f('ix_false_positive_feedbacks_question_id'), table_name='false_positive_feedbacks')
    op.drop_index(op.f('ix_false_positive_feedbacks_performed_by'), table_name='false_positive_feedbacks')
    op.drop_index(op.f('ix_false_positive_feedbacks_is_deleted'), table_name='false_positive_feedbacks')
    op.drop_index(op.f('ix_false_positive_feedbacks_id'), table_name='false_positive_feedbacks')
    op.drop_table('false_positive_feedbacks')
    # ### end Alembic commands ###
