"""Add is_cta to Survey

Revision ID: c2da89bc5ecd
Revises: c1d2e3f4a5b6
Create Date: 2026-09-17 23:22:45.153841
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c2da89bc5ecd'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('is_cta', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_surveys_is_cta'), 'surveys', ['is_cta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveys_is_cta'), table_name='surveys')
    op.drop_column('surveys', 'is_cta')
    # ### end Alembic commands ###
