"""add config to survey questions

Revision ID: e83498dc29d1
Revises: 3f3ca600cf33
Create Date: 2026-07-11 16:29:03.662424
"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e83498dc29d1'
down_revision = '3f3ca600cf33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'survey_questions',
        sa.Column('config', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_questions', 'config')
    # ### end Alembic commands ###
