"""Add is_required to survey question

Revision ID: f5ffd2f1a00b
Revises: e83498dc29d1
Create Date: 2026-07-16 01:34:47.525347
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f5ffd2f1a00b'
down_revision = 'e83498dc29d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'survey_questions',
        sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_questions', 'is_required')
    # ### end Alembic commands ###
